//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Computer_service.Views
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ComputerServiceAAAEntities : DbContext
    {
        public ComputerServiceAAAEntities()
            : base("name=ComputerServiceAAAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brand> Brand { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Contract> Contract { get; set; }
        public virtual DbSet<CPU> CPU { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<GPU> GPU { get; set; }
        public virtual DbSet<Motherboard> Motherboard { get; set; }
        public virtual DbSet<PSU> PSU { get; set; }
        public virtual DbSet<RAM> RAM { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<Table_part> Table_part { get; set; }
        public virtual DbSet<TB_Services> TB_Services { get; set; }
        public virtual DbSet<Technic> Technic { get; set; }
        public virtual DbSet<Technic_type> Technic_type { get; set; }
        public virtual DbSet<Organization> Organization { get; set; }
    }
}
