
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Computer_service.Models
{

using System;
    using System.Collections.Generic;
    
public partial class GPU
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public GPU()
    {

        this.Technic = new HashSet<Technic>();

    }


    public int GPU_id { get; set; }

    public string Name_GPU { get; set; }

    public int Brand_id { get; set; }



    public virtual Brand Brand { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Technic> Technic { get; set; }

}

}
