//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Computer_service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        public string Organization_type { get; set; }
        public string Organization_name { get; set; }
        public string Organization_address { get; set; }
        public string Organization_discription { get; set; }
    }
}
