
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Computer_service.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TB_Services
{

    public int TB_Services_Id { get; set; }

    public int Service_id { get; set; }

    public int Entry_number { get; set; }



    public virtual Service Service { get; set; }

    public virtual Table_part Table_part { get; set; }

}

}
